name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          GOBIN=$PWD/bin go install github.com/golang/mock/mockgen@v1.5.0
          ./bin/mockgen -destination mock/mock_sqsclient.go github.com/aws/aws-sdk-go/service/sqs/sqsiface SQSAPI
          go get -v -t

      - name: Test
        run: go test

      - name: Build
        run: go build .