name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -t -d ./...

      - name: Test
        run: |
          which go
          export
          ls $GOROOT/bin
          $GOROOT/bin/mockgen -destination mock/mock_sqsclient.go github.com/aws/aws-sdk-go/service/sqs/sqsiface SQSAPI
          go test

      - name: Build
        run: go build .